### ISSUE TITLE
Unable to set 'expires_in' for token

### ISSUE THREAD

**Issue by aturkewi** [docusign/docusign-esign-ruby-client#102]
When I generate my token:
```
 api_client.request_jwt_user_token(
      ENV["DOCUSIGN_JWT_INTEGRATION_KEY"],
      ENV["DOCUSIGN_IMPERSONATED_USER_GUID"],
      ENV["DOCUSIGN_RSA_PRIVATE_KEY"],
      60,
      "signature impersonation"
    )
```
It doesn't matter what the 4th arg is. [The code](https://github.com/docusign/docusign-esign-ruby-client/blob/master/lib/docusign_esign/client/api_client.rb#L446) always sets it to 3600.

Also, for what it's worth, the syntax of the example here https://developers.docusign.com/docs/esign-rest-api/sdk-tools/ruby/auth/ (`token = api_client.request_jwt_user_token(Rails.configuration.jwt_integration_key, Rails.configuration.impersonated_user_guid, rsa_pk, expires_in=3600, "signature impersonation")`) does not need the `expires_in=`.

**Comment by EdwinMoralesDS** [comment]
The expires_in variable has a different use then you may expect. The value that is provide in this request is only used for the JWT assertion that we use to create an Access token. The expiration of JWT assertion does not have any impact on when the Access token expires.  All JWT Access tokens generated will always be valid for 36000 seconds regardless of when the JWT assertion is set to expire. 

For example if you set the expires_in  value to 60, you can use the same JWT assertion(the "token" variable) to generate new access tokens for the next 60 seconds. After the 60 seconds pass you will need a new JWT assertion to get new Access tokens. Any Access token generated during the 60 seconds  will be valid for 1 hour after they are generated.

It is not possible to modify the expiration of the Access token that is generated with this process

**Comment by aturkewi** [comment]
Thanks for the fast response @EdwinMoralesDS 

I don't entirely understand the different between the expiration of the JWT assertion compared to the JWT token. I had expected the token to expire with the passed in `expires` on because that was getting written into the token token's claim [here](https://github.com/docusign/docusign-esign-ruby-client/blob/master/lib/docusign_esign/client/api_client.rb#L471). 

I'll do a little bit more research to better understand this. But still, I'm not sure that the code is correct for being able to pass in the `expires_in` value:
`expires_in = 3600 if expires_in > 3600` ([source](https://github.com/docusign/docusign-esign-ruby-client/blob/master/lib/docusign_esign/client/api_client.rb#L453))

If I test this out with different values, this is what I get:
Less than 3600 we get `nil`
```
2.7.2 :004 > expires_in = 60
 => 60
2.7.2 :005 > 3600 if expires_in > 3600
 => nil
```

More than 3600 we get 3600:
```
2.7.2 :006 > expires_in = 1000000
 => 1000000
2.7.2 :007 > 3600 if expires_in > 3600
 => 3600
```

So I suppose I still don't understand what is supposed to be happening, but this logic doesn't seem quite right.

**Comment by EdwinMoralesDS** [comment]
@aturkewi   can you try to run the following code:

`expires_in = 60;
expires_in = 3600 if expires_in > 3600;
puts  expires_in`

**Comment by aturkewi** [comment]
Oh my goodness 🤦 Thank you for that code example. I was misreading that line in the source.

I had read it as `expires_in = (3600 if expires_in > 3600)` (where `expires_in` was being reset to the right side of the `=`). But I see now that it's really `(expires_in = 3600) if (expires_in > 3600)` (where `expires_in` is only being reset if it's too large). 

Well that was embarrassing. I appreciate you taking the time to help me better understand this. I'll go ahead and close this out. Thank you again.
