### ISSUE TITLE
ListStatus not accepting envelope_ids (regression)

### ISSUE THREAD

**Issue by brettwgreen** [docusign/docusign-esign-ruby-client#91]
This was referenced in closed issue: https://github.com/docusign/docusign-esign-ruby-client/issues/15

I am on version 3.11.0 of the gem, and the issue seems identical to the one claimed to be 'fixed'.

Namely, if I call `list_status` with only envelope_ids as so:
```
envelope_api = DocuSign_eSign::EnvelopesApi.new(api_client)
request = DocuSign_eSign::EnvelopeIdsRequest.new
request.envelope_ids = envelope_ids # envelope_ids is an array of envelope id strings
response = envelope_api.list_status(login_account.account_id, request)
```

I get the error: 
> The request contained at least one invalid parameter. Query parameter 'from_date' must be set to a valid DateTime, or 'envelope_ids' or 'transaction_ids' must be specified.

If I add in the from_date, I don't get the error, but the envelope_ids are ignored.

Note that have essentially the same problem with the `list_status_changes` method as well.

**Comment by brettwgreen** [comment]
After much mucking around and exploration of the raw HTTP API, I figured out that the ruby API does not want an array, but a comma separated list...

So this works, given that `envelope_ids` variable is an array of strings
```
options = DocuSign_eSign::ListStatusOptions.new
options.envelope_ids = envelope_ids.join(",")
envelope_statuses = envelope_api.list_status(account_id, {}, options)
```

Similarly, if you want to use the `list_status_changes` method:
```
options = DocuSign_eSign::ListStatusChangesOptions.new
options.envelope_ids = envelope_ids.join(",")
envelope_statuses = envelope_api.list_status_changes(account_id, options)
```

Advantage of the latter is it provides more detail on the individual signer statuses...

**Comment by HobbyProjects** [comment]
Glad you were able to resolve your issue here.
